[package]
name = "immovable-object"
version = "0.1.0"
edition = "2021"

[dependencies]
gotham = "0.7.1"
itertools = "0.11.0"
opencv = "0.82.1"
rppal = { version = "0.14.1", features = ["hal", "hal-unproven"] }
tempfile = "3.6.0"
toml = "0.7.6"

[profile.release]
debug = true
