[package]
name = "uts-drc-2023"
version = "0.1.0"
edition = "2021"

[dependencies]
gotham = "0.7.1"
itertools = "0.11.0"
opencv = "0.82.1"
rppal = { version = "0.14.1", features = ["hal", "hal-unproven"] }

[profile.release]
debug = true
